/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelplinesRouteImport } from './routes/helplines'
import { Route as NeedsRouteImport } from './routes/needs'
import { Route as ReportRouteImport } from './routes/report'
import { Route as CampsCampIdRouteImport } from './routes/camps.$campId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelplinesRoute = HelplinesRouteImport.update({
  id: '/helplines',
  path: '/helplines',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsRoute = NeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsCampIdRoute = CampsCampIdRouteImport.update({
  id: '/camps/$campId',
  path: '/camps/$campId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/helplines': typeof HelplinesRoute
  '/needs': typeof NeedsRoute
  '/report': typeof ReportRoute
  '/camps/$campId': typeof CampsCampIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/helplines': typeof HelplinesRoute
  '/needs': typeof NeedsRoute
  '/report': typeof ReportRoute
  '/camps/$campId': typeof CampsCampIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/helplines': typeof HelplinesRoute
  '/needs': typeof NeedsRoute
  '/report': typeof ReportRoute
  '/camps/$campId': typeof CampsCampIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/helplines' | '/needs' | '/report' | '/camps/$campId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/helplines' | '/needs' | '/report' | '/camps/$campId'
  id: '__root__' | '/' | '/helplines' | '/needs' | '/report' | '/camps/$campId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelplinesRoute: typeof HelplinesRoute
  NeedsRoute: typeof NeedsRoute
  ReportRoute: typeof ReportRoute
  CampsCampIdRoute: typeof CampsCampIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helplines': {
      id: '/helplines'
      path: '/helplines'
      fullPath: '/helplines'
      preLoaderRoute: typeof HelplinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs': {
      id: '/needs'
      path: '/needs'
      fullPath: '/needs'
      preLoaderRoute: typeof NeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps/$campId': {
      id: '/camps/$campId'
      path: '/camps/$campId'
      fullPath: '/camps/$campId'
      preLoaderRoute: typeof CampsCampIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelplinesRoute: HelplinesRoute,
  NeedsRoute: NeedsRoute,
  ReportRoute: ReportRoute,
  CampsCampIdRoute: CampsCampIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
